# Databricks notebook source
master_string = 'THIS IS A STRING CREATED ON THE MASTER BRANCH. WHEN I CREATE A BRANCH I SHOULD BE ABLE TO SEE THIS CELL'

# COMMAND ----------

dev_2_string = 'THIS IS A STRING CREATED ON DEV_2 BRANCH. WHEN I GO BACK TO MASTER I SHOULD NOT BE ABLE TO SEE IT.'

# COMMAND ----------


