# Databricks notebook source
master_string = 'THIS IS A STRING CREATED ON THE MASTER BRANCH. WHEN I CREATE A BRANCH I SHOULD BE ABLE TO SEE THIS CELL'

# COMMAND ----------

dev_1_string = 'THIS IS A STRING CREATED ON DEV_1 BRANCH. WHEN I SAVE THIS FILE AND GO BACK TO MASTER, I SHOULD NOT BE ABLE TO SEE THIS CELL AT ALL.'

# COMMAND ----------


